apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.20 # atlas.local
      - ip: 192.168.1.22 # hermes.local
      - ip: 192.168.1.63 # apollo.local
    ports:
      - port: 49152
