return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
      auto_install = true,
      sync_install = false,
      ensure_installed = {
        "astro",
        "bash",
        "c",
        "cpp",
        "css",
        "dockerfile",
        "elixir",
        "git_config",
        "gitcommit",
        "git_rebase",
        "gitignore",
        "gitattributes",
        "go",
        "html",
        "heex",
        "helm",
        "javascript",
        "jinja",
        "jinja_inline",
        "jsdoc",
        "json",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "nix",
        "ocaml",
        "python",
        "regex",
        "rust",
        "sql",
        "styled",
        "terraform",
        "tmux",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
      },
      highlight = { enable = true },
      indent = { enable = true },
    }
  }
}
